spring:
  application:
    name: gateway-setup
  cloud:
    gateway:
      routes:
        - id: TASKMANAGER
          uri:
            lb://TASKMANAGER
          predicates:
            - Path=/auth/**, /users/**, /api/users/**, /

        - id: TASKSERVICE
          uri:
            lb://TASKSERVICE
          predicates:
            - Path=/api/tasks/**, /tasks/**

        - id: SUBMISSION
          uri:
            lb://SUBMISSION
          predicates:
            - Path=/api/submissions/**, /submissions/**

      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"

server:
  port: 5000

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/